config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { sessions: 'sessions' }
  get 'home/index'
  get 'home/photo'
  root 'home#index'

  get 'site' => 'home#site', controller: 'home'

  namespace :admin do
    get 'dashboard' => "dashboard#index", as: 'dashboard'
    resources :service_cases
    resources :members
    resources :attachments
    resources :system_configurations do
      collection do
        get :web_site_config
        post :web_site_config
        get :company_info_config
        post :company_info_config
      end
    end

    resources :news_trends
  end


  resources :service_cases
  resources :members
  resources :news_trends
end

app/models/news_trend.rb
class NewsTrend < ApplicationRecord
  mount_uploader :cover_image, AvatarUploader
  validates :title_zh, :title_en, presence: {message: "标题不能为空"}



  def title
    case I18n.locale.to_s.downcase
    when "en"
      self.title_en.to_s
    else
      self.title_zh.to_s
    end
  end

  def phrase
    case I18n.locale.to_s.downcase
    when "en"
      self.phrase_en.to_s
    else
      self.phrase_zh.to_s
    end
  end

  def content
    case I18n.locale.to_s.downcase
    when "en"
      self.content_en
    else
      self.content_zh
    end
  end


  def scaned
    update(scan_count: self.scan_count.to_i+1)
  end
end

app/controllers/admin/news_trends_controller.rb
module Admin
  class NewsTrendsController < AdminController
    before_action :set_news_trend, only: [:show, :edit, :update, :destroy]

    def index
      @news_trends = NewsTrend.all.order("created_at desc").paginate(:per_page => 20, :page => params[:page])
    end

    def show
    end

    def new
      @news_trend = NewsTrend.new
    end

    def edit
    end

    def create
      @news_trend = NewsTrend.new(news_trend_params)

      if @news_trend.save
        redirect_to admin_news_trend_path(@news_trend), notice: 'News trend was successfully created.'
      else
        render :new
      end
    end

    def update
      if @news_trend.update(news_trend_params)
        redirect_to admin_news_trend_path(@news_trend), notice: 'News trend was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @news_trend.destroy
      redirect_to news_trends_url, notice: 'News trend was successfully destroyed.'
    end

    private
      def set_news_trend
        @news_trend = NewsTrend.find(params[:id])
      end

      def news_trend_params
        params.require(:news_trend).permit(:title_zh, :title_en, :content_zh, :content_en, :cover_image, :scan_count, :is_published, :phrase_zh, :phrase_en)
      end
  end
end

app/controllers/news_trends_controller.rb
class NewsTrendsController < ApplicationController
  before_action :set_news_trend, only: [:show]

  def index
    @news_trends = NewsTrend.all.where(is_published: true).order("created_at desc").paginate(:per_page => 10, :page => params[:page])
  end

  def show
    @news_trend.scaned if @news_trend.present?
  end

  private
    def set_news_trend
      @news_trend = NewsTrend.find(params[:id])
    end
end

app/helpers/news_trends_helper.rb
module NewsTrendsHelper
end

app/views/admin/news_trends/_form.html.slim
- url = @news_trend.new_record? ? admin_news_trends_path : admin_news_trend_path(@news_trend)
= form_for(@news_trend, url: url, html:{class: "horizontal_form", :multipart => true}) do |f|
  .form-group
    = f.label :title_zh, "标题_中文"
    = f.text_field :title_zh, class: "form-control"
  .form-group
    = f.label :title_en, "标题_英文"
    = f.text_field :title_en, class: "form-control"
  .form-group
    = f.label :phrase_zh, "简介_中文"
    = f.text_area :phrase_zh, class: "form-control", rows: 3
  .form-group
    = f.label :phrase_en, "简介_英文"
    = f.text_area :phrase_en, class: "form-control", rows: 3
  .form-group
    = f.label :content_zh, "内容_中文"
    = f.text_area :content_zh, class: "tinymce"
  .form-group
    = f.label :content_en, "内容_英文"
    = f.text_area :content_en, class: "tinymce"
  .form-group
    = f.label :is_published, "是否发布"
    = f.check_box :is_published, class: "form-control"
  .form-group
    = f.label :cover_image, "封面图片"
    = f.file_field :cover_image, class: "form-control"
    div style="color: red"
      = @member.errors.messages[:cover_image].first rescue nil
  .actions = f.submit "保存"


css:
  #content * {
    -webkit-box-sizing: content-box;
    box-sizing: content-box;
  }

  .form-control{
    max-width: 500px;
  }

app/views/admin/news_trends/edit.html.slim
== render 'form'

app/views/admin/news_trends/index.html.slim
h1 新闻动态
= link_to '创建新闻动态', new_admin_news_trend_path, class: "btn btn-small btn-success"
br
br
table.table.table-bordered.table-hover.table-striped
  thead
    tr
      th 编号
      th 标题
      th 创建时间
      th 发布状态
      th 浏览次数
      th

  tbody
    - @news_trends.each do |news_trend|
      tr
        td = news_trend.id
        td = news_trend.title_zh
        td = news_trend.created_at.strftime("%F %R")
        td = news_trend.is_published ? "已经发布" : "未发布"
        td = news_trend.scan_count
        td
          = link_to '详情', admin_news_trend_path(news_trend), class: "btn btn-small btn-default"
          = link_to '编辑', edit_admin_news_trend_path(news_trend), class: "btn btn-small btn-primary"
          = link_to '删除', admin_news_trend_path(news_trend), data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-small btn-danger"
br
br
.pull-right = will_paginate @news_trends

app/views/admin/news_trends/new.html.slim
== render 'form'

app/views/admin/news_trends/show.html.slim
p
  strong Title zh:
  = @news_trend.title_zh
p
  strong Title en:
  = @news_trend.title_en
p
  strong Phrase zh:
  = @news_trend.phrase_zh
p
  strong Phrase en:
  = @news_trend.phrase_en
p
  strong Content zh:
  = @news_trend.content_zh
p
  strong Content en:
  = @news_trend.content_en
p
  strong Scan count:
  = @news_trend.scan_count
p
  strong Is Published:
  = @news_trend.is_published