config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { sessions: 'sessions' }
  get 'home/index'
  get 'home/photo'
  root 'home#index'

  get 'site' => 'home#site', controller: 'home'

  namespace :admin do
    get 'dashboard' => "dashboard#index", as: 'dashboard'
    resources :service_cases
    resources :members
    resources :attachments
    resources :system_configurations do
      collection do
        get :web_site_config
        post :web_site_config
        get :company_info_config
        post :company_info_config
      end
    end

    resources :news_trends
  end


  resources :service_cases
  resources :members
  resources :news_trends
end

app/views/admin/shared/_header.html.erb
<header>
  <div class='navbar'>
    <div class='navbar-inner'>
      <div class='container-fluid'>
        <a class='brand' href='<%=admin_dashboard_path%>'>
          <!-- <i class='icon-heart-empty'></i> -->
          <%=image_tag("icon.png")%>
          <span class='hidden-phone'>LandSpace Design</span>
        </a>
        <a class='toggle-nav btn pull-left' href='#'>
          <i class='icon-reorder'></i>
        </a>
        <ul class='nav pull-right'>
          <li class='dropdown dark user-menu'>
            <a class='dropdown-toggle' data-toggle='dropdown' href='#'>
              <img alt='Mila Kunis' height='23' src='<%=image_path("victor1.jpg")%>' width='23' />
              <span class='user-name hidden-phone'><%=current_user.email%></span>
              <b class='caret'></b>
            </a>
            <ul class='dropdown-menu'>
              <li>
                <%=link_to "<i class='icon-signout'></i> Sign out".html_safe, destroy_user_session_path, method: :delete%>
              </li>
            </ul>
          </li>
        </ul>
        <form accept-charset="UTF-8" action="search_results.html" class="navbar-search pull-right hidden-phone" method="get" />
          <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
          <button class="btn btn-link icon-search" name="button" type="submit"></button>
          <input autocomplete="off" class="search-query span2" id="q_header" name="q" placeholder="Search..." type="text" value="" />
        </form>
      </div>
    </div>
  </div>
</header>

app/views/admin/shared/_navbar.html.erb
<div id='main-nav-bg'></div>
<nav class='' id='main-nav'>
  <div class='navigation'>
    <ul class='nav nav-stacked'>
      <li class='' id="dashboard">
        <a href='/admin/dashboard'>
          <i class='icon-dashboard'></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class='' id="service_cases">
        <a href='<%=admin_service_cases_path %>'>
          <i class='icon-folder-open-alt'></i>
          <span>服务案例</span>
        </a>
      </li>
      <li class='' id="members">
        <a href='<%=admin_members_path %>'>
          <i class='icon-group'></i>
          <span>团队成员</span>
        </a>
      </li>
      <li class='' id="news_trends">
        <a href='<%=admin_news_trends_path %>'>
          <i class='icon-edit'></i>
          <span>新闻动态</span>
        </a>
      </li>
      <li class='' id="system_configurations">
        <a class='dropdown-collapse' href='#'>
          <i class='icon-cog'></i>
          <span>系统设置</span>
          <i class='icon-angle-down angle-down'></i>
        </a>
        <ul class='nav nav-stacked'>
          <li class='' id="web_site_config">
            <a href='<%=web_site_config_admin_system_configurations_path %>'>
              <i class='icon-caret-right'></i>
              <span>网站配置</span>
            </a>
          </li>

          <li class='' id="company_info_config">
            <a href='<%=company_info_config_admin_system_configurations_path %>'>
              <i class='icon-caret-right'></i>
              <span>公司信息</span>
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<script>
  $("#<%=controller_name%>").addClass("active");
  if($("#<%=controller_name%>").children(".dropdown-collapse") != undefined){
    $("#<%=controller_name%>").children(".dropdown-collapse").addClass("in");
    $("#<%=controller_name%>").children(".nav").addClass("in");
    $("#<%=action_name%>").addClass("active");
  }
</script>